name: Testing github workflow
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    env:
      STEP1: "Le code vient d'etre poussé sur Github"
    steps:
      - name:  "Etape1-initialisation"
        run : 
          echo "Démarrage du pipeline d'integration continue"
          echo"STEP1 =$STEP1"
      - name:  "Etape2-Recuperation du code"
        run:
          echo "Récuperation du code source"
          echo "STEP2 = ${{vars.VAR2}}"
      - name:  "Etape3-Build"
        run:
          echo"phase de build"
          echo" STEP3=${{secrets.MY_SECRET}}"
      - run: echo "Etape4-Tests"
      - run: echo "Etape5-Packaging"
      - run: echo "Etape6-Fin du pipeline"
      